### ISSUE TITLE
decoupling

### ISSUE THREAD

**Issue by adamplansky** [EndevelCZ/odin#2]
Nelibi se mi jak to je spojeny s pkg cfg

https://github.com/EndevelCZ/odin/blob/e62c429ae6b2f20640ca26997d638eb0e24e250e/tracer/jaeger.go#L11

navrhuji to prejmenovat na:
```go
 func InitJaeger() (*jaeger.Exporter, error)
```
a ty envy vytahnout pomoci tech funkci co jsou definovany v pkg config
```go
config.MapString(target *string, envKey string, defaultValue string)
```

**Comment by rjicha** [comment]
Decoupling je fajn, jen se mi zase nechce na kazdym initu vysosavat dve lajny konfigu navic a ty tam predavat. Co udelat nejaky interface pro JaegerConfig?
